### PR TITLE
javascript callbacks are used to sync fast and boxzoom is included new

### PR DESCRIPTION
**Pull request by Sampad530**
javascript callbacks are used instead of python pullbacks to sync fast and boxzoom is included new.

### CODE REVIEW

**Comment by scrgiorgio** [comment]
@Sampad530 this looks fantastic. Can you do minor changes such as:

- remove print
- move the `linkViews` logic outside the `main.py` (i.e., create a new file or move to an existing file as needed) 
- check for breaking changes for non-sync use cases

Thanks!

**Comment by Sampad530** [comment]
1) removed print commands.
2) moved the link Views logic outside the main.py and kept class "SliceSynchronizer" in "sync_link.py".
3) changed for non-sync use cases.
4) kept default resolution to the maximum on both sides and view dependent "yes".
5) modified "backend.py " for 2D color image and "utils" for removed default color palette.
6)  added a menu at the top level to select the dataset.

**Comment by scrgiorgio** [comment]
@Sampad530 very good.
We need to make sure any change is backward compatible.

Some examples:

- keep showing options as they are and use a config line (or command parameters) for what you need for your specific use case. Example: we have NASA dashboards that will require the same default show options as in the past
-  the same for colorbar/colormap
-  the same for the default palette

Also, as a final step, could you check (*) 2D single field (*) 2D RGB dataset(*) 3D single field (*) 3D RGB dataset to make sure they still work with yesterday's modification? (for 3D test all axes, X, Y, Z)

**Comment by BanikSampad** [comment]
Solved:
- kept showing options as they are for all use cases
- kept the same for colorbar, palettes and default palette.
- worked for the single channel and RGB datasets of 2D data and 3D data.

**Pull request merged**
